[package]
name = "ledctl"
version = "0.1.5"
edition = "2024"
authors = ["Thor Høgås <thor@roht.no>"]
homepage = "https://github.com/thor/ledctl"
repository = "https://github.com/thor/ledctl"

[lib]
name = "ledctl"
path = "src/lib.rs"

[[bin]]
name = "ledctl"
path = "src/main.rs"

[dependencies]
iced = "0.14"
core-foundation-sys = "0.8"

[profile.release]
strip = "symbols"      # Automatically strip symbols from the binary
opt-level = "z"        # Optimize for size (use "s" if "z" is not smaller)
lto = true             # Enable Link Time Optimization
codegen-units = 1      # Reduce parallel code generation units for better optimization
incremental = false    # Disable incremental compilation for final builds
